### ISSUE TITLE
missing torrent download icon when artifact name contains spaces

### ISSUE THREAD

**Issue by leoschweizer** [JetBrains/teamcity-torrent-plugin#2]
spaces in the filename of the published artifact break the torrent JavaScript functionality. The torrent icon appears when the filename doesn't contain spaces.

I just installed this nice plugin in my TeamCity 9.0.1 deployment (or more specifically, the version which is provided [here](https://confluence.jetbrains.com/display/TW/Torrent+plugin)). I've enabled the two torrent sharing settings in the admin menu and it displays that it currently announces 1 torrent, which is correct, since there is only one suitable build artifact right now. 

However, I fail to find a download link for the torrent file for this artifact. According to [this post](http://blog.jetbrains.com/teamcity/2013/11/teamcity-torrent-plugin-2/), it should appear in the artifact popup, but it doesn't. When inspecting the HTML source code, I can see that the class `torrent-handled` has been added to the popup, but there are no HTML elements which would provide anything like that. 

Is this plugin not yet compatible with TeamCity 9 or what might I be missing?

**Comment by paksv** [comment]
If you go to build's artifacts tab, then show hidden artifacts, can you see the torrent directory and a torrent file in it?
Also, by default only files larger than 10Mb are seeded as torrents.

**Comment by leoschweizer** [comment]
Yes, the torrent file is there, and it also works (when using it to actually download the file).

**Comment by paksv** [comment]
are there any JS errors? Can you try another browser?

**Comment by leoschweizer** [comment]
I've tried Chrome 39 and Safari 8.0.2, both behave in the same way. Yes there are JS warnings and errors. The warnings are related to missing websockets support, the error indicates a cache miss. Here is the complete console output:

```
INFO Clean all data under element tabsContainer
ERROR WebSocket connection to 'wss://.../teamcity/app/subscriptions?X-Atmosphere-tracking-id=0&X-Atm…-atmo-protocol=true&browserLocationHost=https%3A%2F%2F...%2Fteamcity' failed: Error during WebSocket handshake: Unexpected response code: 501
WARN Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). 
WARN Websocket closed, wasClean: false
INFO Websocket failed. Downgrading to Comet and resending
INFO WebSocket is not supported
ERROR https://.../teamcity/overview.html Failed to load resource: net::ERR_CACHE_MISS
```

However, all of this already occurs at page load time. Opening the artifacts popup doesn't trigger any JS output.

**Comment by paksv** [comment]
What does https://.../teamcity/torrentLinks.html?buildId=<server_unique_build_id> for the desired build return?

**Comment by leoschweizer** [comment]
This returns an empty HTTP 200 (also if I put in a non-existing build id)

**Comment by paksv** [comment]
please double check that "Allow users to download artifacts via a BitTorrent client" is checked under /admin/admin.html?item=torrentSettings

**Comment by leoschweizer** [comment]
Yes, the box is checked. I've also tried unchecking, saving, and checking it again. It didn't have any effect.

**Comment by paksv** [comment]
How does <TC_DATA_DIR>/config/torrent-plugin.properties file look like?

Also, have you tried correct buildId for this: "torrentLinks.html?buildId=<>". It is numeric only the same as in this URL: /viewLog.html?buildId=3719&tab=buildResultsDiv&buildTypeId=One_AlwaysFail (when you click on build from the build configuration page).

**Comment by leoschweizer** [comment]
You are right, I used the wrong ID - with the correct build ID, the URL from above returns the artifact file name as plain text.

Here's the properties file:

```
#Mon Jan 19 15:19:26 CET 2015
torrent.transport.enabled=true
torrent.download.enabled=true
torrent.enabled=true
```

**Comment by paksv** [comment]
Please go to build's artifacts tab, open javascript console and execute the following function:
BS.Torrents._injectTorrentLinks('#artifactsTree',3654);
where 3654 is a buildId like above

**Comment by leoschweizer** [comment]
I can tell you what the source of the error is: spaces in the filename of the published artifact break the torrent JavaScript functionality. The torrent icon appears when the filename doesn't contain spaces.

**Comment by paksv** [comment]
cool, thx

**Comment by paksv** [comment]
https://teamcity.jetbrains.com/repository/download/TeamCityPluginsByJetBrains_TorrentArtifactsMirrorPlugin_TorrentPluginTeamcity81x/383197:id/torrent-plugin.zip

**Comment by leoschweizer** [comment]
thanks for the fix :+1:
